# Site settings
title: Shane Acoveno
description: Portfolio of Shane Acoveno
# baseurl: "/main" # the subpath of your site, e.g. /blog
# url: "http://shaneacoveno.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Shane Acoveno
user_description: Computer Science student at Lehigh University
user_title: Software Developer
email: shaneacoveno@gmail.com
twitter_username: shaneacoveno
github_username:  shaneacoveno
gplus_username:  shaneacoveno

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
