# Site settings
title: Shane Acoveno
description: A portfolio of Lehigh Computer Science student Shane Acoveno
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "http://shaneacoveno.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Shane Acoveno
user_description: A portfolio of Lehigh Computer Science student Shane Acoveno
user_title: Studing Computer Science at Lehigh University
email: shaneacoveno@gmail.com
twitter_username: shaneacoveno
github_username:  shaneacoveno
gplus_username:  shaneacoveno

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
